spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ambraj/codingshuttle-linkedin-app-config-server
          password: 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
          username: ambraj
          default-label: main

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 8888
